leanprover/elan

src/elan/config.rs
src/elan/errors.rs

When installed as a system package, the `lean` proxy shows an unhelpful error message when run the first time:
```
± lean
error: no default toolchain configured
```
This PR augments the error message by suggesting to run `elan toolchain install nightly`, which seems like the most reasonable choice at the moment.

More friendly welcome message

---

src/elan-dist/src/dist.rs
src/elan-dist/src/manifestation.rs
src/elan/toolchain.rs

This pull request strictly adds functionality to lean version selection. It permits a GitHub repository "user/repo" combination, followed by a colon, to prefix the version string which can be specified as the `lean_version`.
For example, if `lean_version = "khoek/klean:3.4.1"` (naming my random lean fork) was to appear in the `leanpkg.toml` of a project, then elan will now instead fetch the release from the right page under https://github.com/khoek/klean, expecting that the release is packaged and named exactly as is currently the format in the `leanprover/lean` mainline. The shorthand tracking labels `lean_version = "khoek/klean:stable"` and `lean_version = "khoek/klean:nightly"` are also kept available, with the assumption that when `nightly` is specified we should append "-nightly" to …

Add colon-delimited custom toolchain origins

---

src/elan-cli/main.rs
src/elan-cli/self_update.rs

The tempdir crate has been [deprecated](https://crates.io/crates/tempdir) in favour of tempfile.
This PR switches elan to use tempfile instead of tempdir.

Replace tempdir with tempfile

---

.github/workflows/ci.yml
elan-init.ps1

The error code was getting lost in the powershell script `elan-init-ps1`, so I fixed it and while I was at it I added a new -PromptOnError option so I don't have to do any tricky logic in the leanInstaller typescript in the vscode extension.
Related to https://github.com/leanprover/vscode-lean4/pull/157

fix win error code

---

elan-init.ps1

**Note:** in order to ensure I do not break the vscode-lean4 extension I will do this in 2 stages.  First is to add only new options then I can move vscode extension over to those then later to remove the old options (-NoMenu and -PromptOnError).
Chris Lovett: From your discussion in https://github.com/leanprover/vscode-lean4/pull/151 let me summarize:
- add powershell -NoModifyPath to map to the no-modify-path elan-init option (hmmm, the vscode extension probably should be using this option).
- remove -PromptOnError since elan-init doesn't have that option (and do this part in vscode extension).
- change -NoPrompt to -NoMenu to match the -no-prompt option in elan-init.
Sebastian Ullrich: Okay, that sounds acceptable. Whether the extension should modify the path is a good question. I …

fix: make command line consistent (part 1)

---

elan-init.ps1

When called by the VSCode extension, Windows Server 2016 defaults to SSL3.0/TLS1.0 and will not download files using `Invoke-WebRequest`. BITS does not have this issue. Have fixed the issue in https://github.com/leanprover/vscode-lean4/pull/246, but didn't realise it was here, too.
Switched the download for the zip from `Invoke-WebRequest` to `Start-BitsTransfer`.
Also, [linked directly to the latest release](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases) (so `Get-RedirectUrl` is no longer required), and added the `ElanVersion` parameter in case somebody wants to download a specific version of elan. It continues to default to downloading "latest".
Have tested on Windows 10, Server 2016, and Server 2019.

Fix for Windows Server 2016 download using VSCode extension

---

src/elan-cli/common.rs

This fix adds a second message, in case we want to install the default version of lean.

fix: when toolchains are empty, message is confusing

---

README.md

Thanks a lot for making this project!
Recently, I have made an update to `homebrew-core`'s `elan-init` formula (https://github.com/Homebrew/homebrew-core/pull/127594) that removes the x86-only restriction, facilitating the binary distribution of `elan` on ARM Macs. I've tested it myself on my ARM Mac and it works like a charm.
Thus, I think it would be appropriate to update `elan`'s README accordingly.

doc: installing with `brew` on ARM Macs

---

src/elan-cli/download_tracker.rs

```pwsh
$ elan update stable
info: syncing channel updates for 'stable'
info: latest update on stable, lean version v4.0.0-m5
info: downloading component 'lean'
6.9 MiB / 139.1 MiB (  5 %)   0 B/s ETA: Unknown                 19.1 MiB / 139.1 MiB ( 14 %)   6.9 MiB/s ETA:  17 s
30.2 MiB / 139.1 MiB ( 22 %)   9.5 MiB/s ETA:  11 s                 41.4 MiB / 139.1 MiB ( 30 %)  10.1 MiB/s ETA:  10 s                 52.5 MiB / 139.1 MiB ( 38 %)  10.3 MiB/s ETA:   8 s                 63.6 MiB / 139.1 MiB ( 46 %)  10.5 MiB/s ETA:   7 s                 74.7 MiB / 139.1 MiB ( 54 %)  11.3 MiB/s ETA:   6 s                 86.0 MiB / 139.1 MiB ( 62 %)  11.1 MiB/s ETA:   5 s                 97.1 MiB / 139.1 MiB ( 70 %)  11.2 MiB/s ETA:   4 s
108.3 MiB / 139.1 MiB ( 78 %)  11.2 MiB/s ETA:   3 s …
```

fix display glitch of download progress

---

elan-init.sh

Closes #114.
> But could you first check what upstream rustup does and copy that if applicable?
Reference code: https://github.com/rust-lang/rustup/blob/79e88a2d422afb33acc247ff19c467667f458df7/rustup-init.sh#L309. I made some edits:
- instead of initializing a variable, I raised an error (rust supports musl, lean does not https://github.com/leanprover/lean4/issues/2931);
- this time around we do not want to check if musl is, but if glibc is not.

Add glibc dependency check

---

README.md

There's a weird behavior of curl in PowerShell 5.1: when running the first command in the instructions, the created file is named `--location` instead of `elan-init.ps1`.
I checked that curl works properly in Command Prompt or PowerShell 7.4.1. To install elan, Windows users should use Command Prompt or PowerShell ≥ version 7.4.1.
---
This pull request is a revision of https://github.com/leanprover/elan/pull/119. See also the [discussion][0] about this PR in the Lean Zulip chat.
[0]: https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/elan.23119.20doc.3A.20fix.20installation.20instructions.20for.20Windows/near/419009910

doc: clarify installation instructions for Windows

---

src/download/src/lib.rs
src/elan-cli/self_update.rs
src/elan-dist/src/download.rs
src/elan-dist/src/manifestation.rs
src/elan-utils/src/utils.rs
src/elan/config.rs
src/elan/toolchain.rs

```
$ elan toolchain install stable
info: syncing channel updates for 'stable'
info: latest update on stable, lean version v4.5.0
info: downloading component 'lean'
150.1 MiB / 150.1 MiB (100 %)  68.2 MiB/s ETA:   0 s
info: installing component 'lean'
^C
$ ls -R ~/.elan/toolchains/stable.tmp | wc -l
1444
$ elan toolchain install stable
info: syncing channel updates for 'stable'
info: latest update on stable, lean version v4.5.0
info: downloading component 'lean'
150.1 MiB / 150.1 MiB (100 %)  69.2 MiB/s ETA:   0 s
info: installing component 'lean'
stable installed
$ ls -R ~/.elan/toolchains/stable | wc -l
2859
```

Create toolchain directory atomically

---

src/elan-cli/elan_mode.rs
src/elan-cli/self_update.rs
src/elan-dist/src/notifications.rs
src/elan/install.rs
src/elan/lib.rs

```
$ elan toolchain install stable
info: Version 3.0.0 of elan is available! Use `elan self update` to update.
...
```

feat: check for self-updates during toolchain downloads

---

.github/workflows/ci.yml
elan-init.sh
fetch_nixos_patch.sh
src/elan-cli/common.rs
src/elan-cli/elan_mode.rs
src/elan-cli/help.rs
src/elan-cli/proxy_mode.rs
src/elan-cli/self_update.rs
src/elan-cli/setup_mode.rs
src/elan-dist/src/component/package.rs
src/elan-dist/src/dist.rs
src/elan-dist/src/manifestation.rs
src/elan-dist/src/notifications.rs
src/elan-utils/src/errors.rs
src/elan-utils/src/notifications.rs
src/elan-utils/src/utils.rs
src/elan/config.rs
src/elan/errors.rs
src/elan/install.rs
src/elan/notifications.rs
src/elan/settings.rs
src/elan/toolchain.rs

This also gets rid of the `update-hashes/` directory (it won't literally get rid of it on existing installs but the contents do not matter anymore).

Eagerly resolve toolchains to canonical, fixed reference

---

Cargo.lock
build.rs
src/download/src/lib.rs
src/elan-cli/common.rs
src/elan-cli/download_tracker.rs
src/elan-cli/elan_mode.rs
src/elan-cli/help.rs
src/elan-cli/log.rs
src/elan-cli/proxy_mode.rs
src/elan-cli/self_update.rs
src/elan-cli/setup_mode.rs
src/elan-cli/term2.rs
src/elan-dist/src/component/package.rs
src/elan-dist/src/dist.rs
src/elan-dist/src/errors.rs
src/elan-dist/src/lib.rs
src/elan-dist/src/manifestation.rs
src/elan-dist/src/notifications.rs
src/elan-utils/src/notifications.rs
src/elan-utils/src/utils.rs
src/elan/config.rs
src/elan/errors.rs
src/elan/gc.rs
src/elan/install.rs
src/elan/lib.rs
src/elan/settings.rs
src/elan/toolchain.rs

seeing some time related failure 
```
error[E0282]: type annotations needed for `Box<_>`
--> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.20/src/format_description/parse/mod.rs:83:9
|
83 |     let items = format_items
|         ^^^^^
...
86 |     Ok(items.into())
|              ---- type must be known at this point
|
help: consider giving `items` an explicit type, where the placeholders `_` are specified
|
83 |     let items: Box<_> = format_items
|              ++++++++
```
has been addressed with 0.3.36, https://github.com/time-rs/time/issues/693

chore: update to build with rust 1.80

---

src/elan/toolchain.rs

related: #99 
Currently, the remote toolchain reference feature on GitHub does not support repositories with underscores in their names. This limitation affects repositories like `leanprover-community/mathematics_in_lean`.

Support for toolchain origins with underscores

---

Cargo.lock
src/elan-dist/Cargo.toml
src/elan-dist/src/lib.rs
src/elan-dist/src/manifestation.rs
src/elan-dist/src/notifications.rs

```
$ elan install nightly
info: waiting for previous installation request to finish (/home/sebastian/.elan/toolchains/leanprover--lean4-nightly---nightly-2024-11-23.lock, held by PID 2508083
)
leanprover/lean4-nightly:nightly-2024-11-23 installed
```

fix: per-toolchain installation lock

---

Cargo.lock
src/elan-cli/json_dump.rs
src/elan-dist/Cargo.toml
src/elan-dist/src/dist.rs
src/elan-dist/src/lib.rs
src/elan/config.rs
src/elan/toolchain.rs

```
"default": {
"unresolved": {
"Remote": {
"origin": "leanprover/lean4-nightly",
"release": "nightly",
"from_channel": "nightly"
}
},
"resolved": {
"Ok": "leanprover/lean4-nightly:nightly-2024-11-23"
}
},
"active_override": {
"unresolved": {
"Remote": {
"origin": "leanprover/lean4",
"release": "stable",
"from_channel": "stable"
}
},
"reason": "Environment"
},
"resolved_active": {
"Ok": "leanprover/lean4:v4.13.0"
}
```

chore: more unresolved dump-state output, do not resolve during override lookup

---

src/elan-cli/json_dump.rs
src/elan/config.rs
src/elan/toolchain.rs

```
$ elan dump-state
"default": {
"unresolved": {
"Remote": {
"origin": "leanprover/lean4",
"release": "stable",
"from_channel": "stable"
}
},
"resolved": {
"live": {
"Ok": "leanprover/lean4:v4.14.0"
},
"cached": {
"Ok": "leanprover/lean4:v4.9.0"
}
}
},
"active_override": null,
"resolved_active": {
"live": {
"Ok": "leanprover/lean4:v4.14.0"
},
"cached": {
"Ok": "leanprover/lean4:v4.9.0"
}
}
```
```
$ elan dump-state --no-net
"default": {
"unresolved": {
"Remote": {
"origin": "leanprover/lean4",
"release": "stable",
"from_channel": "stable"
}
},
"resolved": {
"live": {
"Err": "Cannot fetch latest release tag under `--no-net`"
},
"cached": {
"Ok": "leanprover/lean4:v4.9.0"
}
}
},
"active_override": null,
"resolved_active": {
"live": {
"Err": "Cannot fetch latest release tag under …
```

feat: differentiate live and cached toolchain resolution in `dump-state`

---

elan-init.ps1

If the download fails the script currently throws away the exception information and prints a generic error. This changes it to also print the exception.

Improve error reporting in elan-init.ps1

---

CHANGELOG.md
Cargo.lock
src/elan-cli/help.rs
src/elan-cli/self_update.rs
src/elan-dist/src/dist.rs
src/elan-dist/src/lib.rs
src/elan-dist/src/manifestation.rs
src/elan-utils/Cargo.toml
src/elan-utils/src/utils.rs
src/elan/toolchain.rs

Makes toolchain URL resolution robust against future GitHub changes and enables use of the `beta` channel to refer to the latest RC release. Also allows for distinguishing between non-existing releases and non-existing assets for a release.

feat: fetch release info and asset URLs from release.lean-lang.org instead of parsing GitHub HTML
